site_name: Bespoken
site_description: A framework for creating constrained LLM applications
site_author: Bespoken Team

repo_url: https://github.com/koaning/bespoken
edit_uri: edit/main/docs/

theme:
  name: material
  icon:
    logo: octicons/terminal-16
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - content.code.copy
    - content.code.annotate
  
  # Use our CSS instead of theme palettes
  palette: {}

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html

nav:
  - index.md
  - Examples:
    - Quickstart: guides/quick-start.md

extra_css:
  - https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;700&display=swap
  - https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css
  - assets/css/custom.css
